# Generated by Django 4.0 on 2021-12-12 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_students_student'),
        ('subject', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(to='student.Student'),
        ),
    ]
