# Generated by Django 4.0 on 2021-12-13 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0004_alter_student_address_alter_student_email'),
        ('subject', '0002_alter_subject_student'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='student',
            field=models.ManyToManyField(blank=True, to='student.Student'),
        ),
    ]
